project_id = "kyblfclgcwbyrawwigsc"

[functions.create-account-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.fetch-og-image]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.get-locations]
verify_jwt = false

[functions.invite-user]
verify_jwt = true

[functions.verify-invite-token]
verify_jwt = false
