project_id = "kyblfclgcwbyrawwigsc"

[functions.create-account-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.fetch-og-image]
verify_jwt = false

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true
